server:
  port: 9000
spring:
  application:
    name: im-service

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/oauth2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    #连接池
    hikari:
      minimum-idle: 5                       #HikariCP在连接池中维护的最小空闲连接数
      maximum-pool-size: 15                 #配置最大池大小
      auto-commit: true                     #t配置从池返回的连接的默认自动提交行为
      idle-timeout: 30000                   #是允许连接在连接池中空闲的最长时间
      pool-name: DatebookHikariCP
      max-lifetime: 120000                  #是池中连接关闭后的最长生命周期
      connection-timeout: 30000             #是客户端等待连接池连接的最大毫秒数
      connection-test-query: SELECT 1
    #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 30000
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置mapper.xml文件所在位置
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名规则，不然某些表的字段名找不到实体类的对应的属性会为 null

#打印 sql
#logging:
#  level:
#    #com.eekj.mapper: debug

